name: Khadeemtheintrovert
favicon: null
layout_spectrum: 0.77973
typography_spectrum: 0.60833
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0500'
    - '#fffffb'
    - '#7093b3'
    - '#fea500'
    - '#7d4c00'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
